In [2]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
from sklearn import linear_model
%matplotlib inline
pd.options.display.float_format = '{:.3f}'.format

# Suppress annoying harmless error.
import warnings
warnings.filterwarnings(action="ignore", module="scipy", message="^internal gelsd")

In [5]:
# Importing our data
data = pd.read_excel('table_8_offenses_known_to_law_enforcement_new_york_by_city_2013.xls', 
                     encoding='latin1', skiprows=list(range(4)))

# Condense and clean our dataset
data = data.rename(index = str, columns={'Murder and\nnonnegligent\nmanslaughter': 'Murder', 'Property\ncrime': "Property_crime"})
propertycrime = data[['City', 'Population', 'Murder', 'Robbery', 'Property_crime']]
propertycrime = propertycrime.dropna()

# Create the new rows for our regression model
propertycrime['Pop_squared'] = propertycrime['Population'] ** 2
propertycrime.loc[propertycrime['Murder'] > 0, 'Murder'] = 1
propertycrime.loc[propertycrime['Robbery'] > 0, 'Robbery'] = 1

# Preview the data
propertycrime.head()

,City,Population,Murder,Robbery,Property_crime,Pop_squared
0,Adams Village,1861.000,0.000,0.000,12.000,3463321.000
1,Addison Town and Village,2577.000,0.000,0.000,24.000,6640929.000
2,Akron Village,2846.000,0.000,0.000,16.000,8099716.000
3,Albany,97956.000,1.000,1.000,4090.000,9595377936.000
4,Albion Village,6388.000,0.000,1.000,223.000,40806544.000